### ISSUE TITLE
Better error msg for incomprehensible bill titles (and better explanation)

### ISSUE THREAD

**Issue by jeremybmerrill** [MinnPost/legislature-tracker#13]
Bill names have to be, it appears, like "SF 789" or "A 5249" to match OpenStates' format. Some states and media outlets seem to cite bills in different ways, e.g. ["A.6357"](http://www.legislativegazette.com/Articles-Top-Stories-c-2013-04-16-83437.113122-Savino-optimistic-medical-marijuana-bill-will-pass-Senate-this-year.html), ["S04236A"](http://assembly.state.ny.us/leg/?term=2013&bn=S04236) or ["A00524"](http://assembly.state.ny.us/leg/?default_fld=%0D%0A&bn=A00524&term=2013&Summary=Y). 

Unless someone wants to write a parser to trim leading zeros, trailing letters and replace separators with spaces, LT should at least offer a better error msg explaining the possible source(s) of the error.

Right now, if you access index-dev.html with an unacceptable bill number as the primary bill number, you get the following error message

```
Uncaught TypeError: Cannot call method 'diff' of undefined    app.js:197
(anonymous function)                                          app.js:197
w.each.w.forEach                                              underscore.1.4.3.min.js:1
s.(anonymous function)                                        backbone.0.9.10.min.js:28
LT.Application.Backbone.Router.extend.makeRecentCategory      app.js:194
(anonymous function)                                          app.js:116
$.jsonp.success                                               app.js:243
```

**Comment by zzolo** [comment]
This has been done with some basic data checking and with more description in the README.
