### ISSUE TITLE
Safari issue

### ISSUE THREAD

**Issue by ockerk** [MinnPost/legislature-tracker#40]
For some reason, all demos, even those available athttp://code.minnpost.com/legislature-tracker/examples/mn-dev.html, as well as the install on my test server suddenly stopped working. Every is stuck on a loading screen. I noticed the one at minnpost.com is working, I'm wondering if there isn't an update to the API that needs to be made?

**Comment by zzolo** [comment]
Hi @ockerk.

I just went to http://code.minnpost.com/legislature-tracker/examples/mn-dev.html and it seemed to work for me just fine.  Let me know if you are still having this issue.

I know the OpenStates API is changing so it will go down some time soon, but it should not have happened yet.

**Comment by ockerk** [comment]
Hi @zzolo.

I am able to access the link through my iPad, however I can now access it on Chrome 31.0.1650.63 and Firefox 25 & 26. It appears the issue solely lies with the computer edition of Safari 7.0 running on OSX 10.9. It works fine through mobile Safari.

How drastic are the upcoming OpenStates API updates?

**Comment by zzolo** [comment]
I am running OSX 10.9 and Safari 7.0 and it works fine for me.  Can you look at the inspector/web tools to see if there are any JS errors popping up for you.

I am not sure of the breadth of the changes, but its essentially a whole new API:
http://docs.opencivicdata.org/en/latest/api/index.html

**Comment by ockerk** [comment]
Three warnings for invalid CSS property declaration on lines 159, 231 and 295 of style.css.

SyntaxError on line one of ServiceLogin. Says “Unexpected token ‘<‘.“

**Comment by ockerk** [comment]
Clicking on the link for the SyntaxError mentioned above in the debugger takes to me a Google Spreadsheet JSON: https://spreadsheets.google.com/feeds/worksheets/0AtX8MXQ89fOKdFNaY1Nzc3p6MjJQdll1VEZwSDkzWEE/public/basic?alt=json-in-script&callback=Tabletop.callbacks.tt138686638605832956&pli=1

**Comment by ockerk** [comment]
I just attempted to load it in Safari and it popped right up. I'm not sure if there was a silent update to Safari? Or what happened. But it's working now.
